spring:
  profiles:
    default: local
  application:
    name: web-app-sample
  messages:
    encoding: UTF-8
  jackson:
    time-zone: "Asia/Tokyo"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3326/web_sample_db?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: password
  devtools:
    restart:
      enabled: true

logging:
  level:
    root: INFO

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: false
    tags-sorter: method
    defaultModelRendering: example
    doc-expansion: list
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
