spring:
  profiles:
    default: local
  application:
    name: web-app-sample
  messages:
    encoding: UTF-8
  jackson:
    time-zone: "Asia/Tokyo"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  devtools:
    restart:
      enabled: false

mybatis:
  type-aliases-package: fjk.app.web.sample.models.infra.entity
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

logging:
  level:
    root: INFO
    fjk.app.web.sample.repository: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: false
    tags-sorter: method
    defaultModelRendering: example
    doc-expansion: list
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
